sudo: required

os:
  - "linux"
  - "osx"

language: node_js

node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install build-essential libxi-dev libglu1-mesa-dev libglew-dev; fi
install:
  - ./build.sh
